### ISSUE TITLE
Error loading libSBML when executing ./Generate.sh in remote directory

### ISSUE THREAD

**Issue by rlecover007** [varnerlab/KwateeServer#1]
Executing ./Generate.sh with a .xml file in a different directory than where ./Generate.sh lives generates the following error: 

Error encountered while attempting to load libSBML:
Please check the value of your LD_LIBRARY_PATH environment variable and/or your 'java.library.path' system property (depending on which one you are using) to make sure it list the directories needed to find the libsbmlj.so library file and libraries it depends upon (e.g., the XML parser).

**Comment by varnerlab** [comment]
Fresh install of the server, libSMBL and the plugin JARs resolved this issue.
